{"config":{"indexing":"full","lang":["en"],"min_search_length":3,"prebuild_index":false,"separator":"[\\s\\-]+"},"docs":[{"location":"","text":"Welcome to MkDocs For full documentation visit mkdocs.org . Commands mkdocs new [dir-name] - Create a new project. mkdocs serve - Start the live-reloading docs server. mkdocs build - Build the documentation site. mkdocs -h - Print help message and exit. Project layout mkdocs.yml # The configuration file. docs/ index.md # The documentation homepage. ... # Other markdown pages, images and other files.","title":"Welcome to MkDocs"},{"location":"#welcome-to-mkdocs","text":"For full documentation visit mkdocs.org .","title":"Welcome to MkDocs"},{"location":"#commands","text":"mkdocs new [dir-name] - Create a new project. mkdocs serve - Start the live-reloading docs server. mkdocs build - Build the documentation site. mkdocs -h - Print help message and exit.","title":"Commands"},{"location":"#project-layout","text":"mkdocs.yml # The configuration file. docs/ index.md # The documentation homepage. ... # Other markdown pages, images and other files.","title":"Project layout"},{"location":"atom_command_not_found/","text":"Probelm atom .git/config -> zsh: command not found: atom Solution from: https://stackoverflow.com/a/68991202 Open Atom Press \u2318 \u21e7 P while focused in an editor pane, the command palette will pop up. Type \"Window: Install Shell Commands\"","title":"Atom command not found"},{"location":"atom_command_not_found/#probelm","text":"atom .git/config -> zsh: command not found: atom","title":"Probelm"},{"location":"atom_command_not_found/#solution","text":"from: https://stackoverflow.com/a/68991202 Open Atom Press \u2318 \u21e7 P while focused in an editor pane, the command palette will pop up. Type \"Window: Install Shell Commands\"","title":"Solution"},{"location":"aws_remove_payment_method/","text":"AWS does not allow you to remove all the payment methods. So the only option is to close the account.","title":"Aws remove payment method"},{"location":"bew_command_not_found/","text":"Problem: After installing homebrew, I am geting this error: Getting error: zsh: command not found: brew Solution: Run echo 'eval $(/opt/homebrew/bin/brew shellenv)' >> /Users/$USER/.zshrc source ~/.zshrc Notes: brew was intalled in /opt/homebrew/ location which was not added to the path automatically. Reference: https://stackoverflow.com/q/36657321","title":"Bew command not found"},{"location":"bew_command_not_found/#problem","text":"After installing homebrew, I am geting this error: Getting error: zsh: command not found: brew","title":"Problem:"},{"location":"bew_command_not_found/#solution","text":"Run echo 'eval $(/opt/homebrew/bin/brew shellenv)' >> /Users/$USER/.zshrc source ~/.zshrc Notes: brew was intalled in /opt/homebrew/ location which was not added to the path automatically. Reference: https://stackoverflow.com/q/36657321","title":"Solution:"},{"location":"chrome_shortcuts/","text":"chrome change/switch profile \u2318 \u21e7 M -> \u2191 \u2193 -> \u23ce","title":"Chrome shortcuts"},{"location":"chrome_shortcuts/#chrome-changeswitch-profile","text":"\u2318 \u21e7 M -> \u2191 \u2193 -> \u23ce","title":"chrome change/switch profile"},{"location":"code_command_not_found/","text":"vscode code command not found Probelm code . -> zsh: command not found: code Solution: from: https://stackoverflow.com/a/39604469 open vs code \u2318 \u21e7 P to open command palette search shell command and select Shell Command: Install 'code' command in PATH","title":"vscode code command not found"},{"location":"code_command_not_found/#vscode-code-command-not-found","text":"","title":"vscode code command not found"},{"location":"code_command_not_found/#probelm","text":"code . -> zsh: command not found: code","title":"Probelm"},{"location":"code_command_not_found/#solution","text":"from: https://stackoverflow.com/a/39604469 open vs code \u2318 \u21e7 P to open command palette search shell command and select Shell Command: Install 'code' command in PATH","title":"Solution:"},{"location":"exasol/","text":"Exasol Find users with a given role select * from exa_dba_role_privs where granted_role = 'MY_ROLE'; Find the schema owner check the owner of the schema unsing: select * from exa_schemas where schema_name = 'MY_SCHEMA'; Find the table owner select * from EXA_USER_TABLES where table_schema = 'MY_SCHEMA' and table_name = 'MY_TABLE'; Exasol any true ref with base(dept, name, is_tech) as ( values ('D1', 'P1', true), ('D1', 'P2', false), ('D2', 'P3', false), ('D2', 'P4', false), ('D3', 'P5', null), ('D4', 'P6', false), ('D4', 'P7', null) ) select dept, any(is_tech) as is_any_tech from base group by dept order by dept; returns DEPT IS_ANY_TECH D1 true D2 false D3 null D4 false","title":"Exasol"},{"location":"exasol/#exasol","text":"","title":"Exasol"},{"location":"exasol/#find-users-with-a-given-role","text":"select * from exa_dba_role_privs where granted_role = 'MY_ROLE';","title":"Find users with a given role"},{"location":"exasol/#find-the-schema-owner","text":"check the owner of the schema unsing: select * from exa_schemas where schema_name = 'MY_SCHEMA';","title":"Find the schema owner"},{"location":"exasol/#find-the-table-owner","text":"select * from EXA_USER_TABLES where table_schema = 'MY_SCHEMA' and table_name = 'MY_TABLE';","title":"Find the table owner"},{"location":"exasol/#exasol-any-true","text":"ref with base(dept, name, is_tech) as ( values ('D1', 'P1', true), ('D1', 'P2', false), ('D2', 'P3', false), ('D2', 'P4', false), ('D3', 'P5', null), ('D4', 'P6', false), ('D4', 'P7', null) ) select dept, any(is_tech) as is_any_tech from base group by dept order by dept; returns DEPT IS_ANY_TECH D1 true D2 false D3 null D4 false","title":"Exasol any true"},{"location":"fastai/","text":"FastAI course: https://course.fast.ai/ Lesson 1 https://course.fast.ai/videos/?lesson=1 https://www.youtube.com/watch?v=_QUEXsHfsA0 Source: https://github.com/fastai/fastbook Error installing fastbook pip install fastbook returns ... Collecting MarkupSafe>=2.0 Using cached MarkupSafe-2.1.1-cp310-cp310-macosx_10_9_universal2.whl (17 kB) Using legacy 'setup.py install' for sentencepiece, since package 'wheel' is not installed. Building wheels for collected packages: tokenizers Building wheel for tokenizers (pyproject.toml) ... error error: subprocess-exited-with-error \u00d7 Building wheel for tokenizers (pyproject.toml) did not run successfully. \u2502 exit code: 1 \u2570\u2500> [51 lines of output] running bdist_wheel running build running build_py creating build creating build/lib.macosx-12.1-arm64-cpython-310 creating build/lib.macosx-12.1-arm64-cpython-310/tokenizers copying py_src/tokenizers/__init__.py -> build/lib.macosx-12.1-arm64-cpython-310/tokenizers ... copying py_src/tokenizers/tools/visualizer-styles.css -> build/lib.macosx-12.1-arm64-cpython-310/tokenizers/tools running build_ext running build_rust error: can't find Rust compiler If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler. To update pip, run: pip install --upgrade pip and then retry package installation. If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain. [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for tokenizers Failed to build tokenizers ERROR: Could not build wheels for tokenizers, which is required to install pyproject.toml-based projects WARNING: You are using pip version 22.0.4; however, version 22.1.2 is available. You should consider upgrading via the '/Users/anil/.../venv/bin/python -m pip install --upgrade pip' command. It seems I need to install rust compiler curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh verify the installation via rustc -h . I needed to close and reopen terminal again. install again pip install fastbook returns ... Using legacy 'setup.py install' for sentencepiece, since package 'wheel' is not installed. Installing collected packages: sentencepiece, murmurhash, cymem, xxhash, typing-extensions, typer, tqdm, threadpoolctl, spacy-loggers, spacy-legacy, smart-open, regex, preshed, pillow, numpy, multidict, langcodes, kiwisolver, joblib, graphviz, fsspec, frozenlist, fonttools, filelock, fastprogress, dill, cycler, catalogue, async-timeout, yarl, torch, srsly, scipy, responses, pydantic, pyarrow, pathy, pandas, multiprocess, matplotlib, huggingface-hub, fastcore, blis, aiosignal, transformers, torchvision, thinc, scikit-learn, fastdownload, aiohttp, spacy, fastai, datasets, fastbook Running setup.py install for sentencepiece ... error error: subprocess-exited-with-error \u00d7 Running setup.py install for sentencepiece did not run successfully. \u2502 exit code: 1 \u2570\u2500> [43 lines of output] ~/.pyenv/versions/3.10.5/lib/python3.10/site-packages/setuptools/dist.py:717: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead warnings.warn( running install running build running build_py creating build creating build/lib.macosx-12.1-arm64-3.10 creating build/lib.macosx-12.1-arm64-3.10/sentencepiece copying src/sentencepiece/__init__.py -> build/lib.macosx-12.1-arm64-3.10/sentencepiece copying src/sentencepiece/sentencepiece_model_pb2.py -> build/lib.macosx-12.1-arm64-3.10/sentencepiece copying src/sentencepiece/sentencepiece_pb2.py -> build/lib.macosx-12.1-arm64-3.10/sentencepiece running build_ext Package sentencepiece was not found in the pkg-config search path. Perhaps you should add the directory containing `sentencepiece.pc' to the PKG_CONFIG_PATH environment variable No package 'sentencepiece' found Cloning into 'sentencepiece'... Note: switching to 'd8711f55d9b2cb9c77a00adcc18108482b29b675'. You are in 'detached HEAD' state. You can look around, make experimental changes and commit them, and you can discard any commits you make in this state without impacting any branches by switching back to a branch. If you want to create a new branch to retain commits you create, you may do so (now or later) by using -c with the switch command. Example: git switch -c <new-branch-name> Or undo this operation with: git switch - Turn off this advice by setting config variable advice.detachedHead to false ./build_bundled.sh: line 15: cmake: command not found ./build_bundled.sh: line 16: nproc: command not found make: *** No targets specified and no makefile found. Stop. make: *** No rule to make target `install'. Stop. Package sentencepiece was not found in the pkg-config search path. Perhaps you should add the directory containing `sentencepiece.pc' to the PKG_CONFIG_PATH environment variable No package 'sentencepiece' found Failed to find sentencepiece pkg-config [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. error: legacy-install-failure \u00d7 Encountered error while trying to install package. \u2570\u2500> sentencepiece note: This is an issue with the package mentioned above, not pip. hint: See above for output from the failure. check if cmake is installed cmake -h -> zsh: command not found: cmake Install cmake brew install cmake Try again pip install fastbook It failed with following log ... ^ In file included from src/sentencepiece/sentencepiece_wrap.cxx:2808: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:642:26: error: no template named 'numeric_limits' bool _FloatBigger = (numeric_limits<_FloatT>::digits > numeric_limits<_IntT>::digits), ^ /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:642:60: error: no template named 'numeric_limits' bool _FloatBigger = (numeric_limits<_FloatT>::digits > numeric_limits<_IntT>::digits), ^ /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:643:18: error: no template named 'numeric_limits' int _Bits = (numeric_limits<_IntT>::digits - numeric_limits<_FloatT>::digits)> ^ /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:643:50: error: no template named 'numeric_limits' int _Bits = (numeric_limits<_IntT>::digits - numeric_limits<_FloatT>::digits)> ^ /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:648:17: error: no template named 'numeric_limits' static_assert(numeric_limits<_FloatT>::radix == 2, \"FloatT has incorrect radix\"); ^ /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:651:25: error: no template named 'numeric_limits' return _FloatBigger ? numeric_limits<_IntT>::max() : (numeric_limits<_IntT>::max() >> _Bits << _Bits); ^ /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:651:58: error: no template named 'numeric_limits' return _FloatBigger ? numeric_limits<_IntT>::max() : (numeric_limits<_IntT>::max() >> _Bits << _Bits); ^ /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:645:25: error: no return statement in constexpr function _LIBCPP_CONSTEXPR _IntT __max_representable_int_for_float() _NOEXCEPT { ^ /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:661:16: error: no template named 'numeric_limits' using _Lim = numeric_limits<_IntT>; ^ /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:664:12: error: use of undeclared identifier '_Lim' return _Lim::max(); ^ /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:665:21: error: use of undeclared identifier '_Lim' } else if (__r <= _Lim::lowest()) { ^ /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:666:12: error: use of undeclared identifier '_Lim' return _Lim::min(); ^ 197 warnings and 12 errors generated. error: command '/usr/bin/clang' failed with exit code 1 [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. error: legacy-install-failure \u00d7 Encountered error while trying to install package. \u2570\u2500> sentencepiece note: This is an issue with the package mentioned above, not pip. hint: See above for output from the failure. try to install sentencepiece via pip directly pip install sentencepiece Still getting the same error as above. Looks like there is no wheel for python 3.10 for mac os and it tries to build it in my local machine. There is a wheel for 3.9 so let's try that. pyenv install 3.9.13 pyenv local 3.9.13 rm -rf venv python -m venv venv source ./venv/bin/activate try again: pip install fastbook Success!! import fastbook -> error ModuleNotFoundError: No module named '_lzma' Let's try the solution as per this post: https://stackoverflow.com/a/69517932 brew install xz pyenv uninstall 3.9.13 pyenv install 3.9.13 rm -rf venv python -m venv venv source ./venv/bin/activate pip install fastbook try again import fastbook -> ... except ModuleNotFoundError: warn(\"Missing `ipywidgets` - please install it\") let's try pip install ipywidgets try again import fastbook This time got warning only ~/.../venv/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: dlopen(~/.../venv/lib/python3.9/site-packages/torchvision/image.so, 0x0006): Symbol not found: __ZN3c106detail19maybe_wrap_dim_slowExxb Referenced from: ~/.../venv/lib/python3.9/site-packages/torchvision/image.so Expected in: ~/.../venv/lib/python3.9/site-packages/torch/lib/libc10.dylib warn(f\"Failed to load image Python extension: {e}\") The notebook from git repo is working now!!","title":"FastAI"},{"location":"fastai/#fastai","text":"course: https://course.fast.ai/","title":"FastAI"},{"location":"fastai/#lesson-1","text":"https://course.fast.ai/videos/?lesson=1 https://www.youtube.com/watch?v=_QUEXsHfsA0 Source: https://github.com/fastai/fastbook","title":"Lesson 1"},{"location":"fastai/#error-installing-fastbook","text":"pip install fastbook returns ... Collecting MarkupSafe>=2.0 Using cached MarkupSafe-2.1.1-cp310-cp310-macosx_10_9_universal2.whl (17 kB) Using legacy 'setup.py install' for sentencepiece, since package 'wheel' is not installed. Building wheels for collected packages: tokenizers Building wheel for tokenizers (pyproject.toml) ... error error: subprocess-exited-with-error \u00d7 Building wheel for tokenizers (pyproject.toml) did not run successfully. \u2502 exit code: 1 \u2570\u2500> [51 lines of output] running bdist_wheel running build running build_py creating build creating build/lib.macosx-12.1-arm64-cpython-310 creating build/lib.macosx-12.1-arm64-cpython-310/tokenizers copying py_src/tokenizers/__init__.py -> build/lib.macosx-12.1-arm64-cpython-310/tokenizers ... copying py_src/tokenizers/tools/visualizer-styles.css -> build/lib.macosx-12.1-arm64-cpython-310/tokenizers/tools running build_ext running build_rust error: can't find Rust compiler If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler. To update pip, run: pip install --upgrade pip and then retry package installation. If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain. [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for tokenizers Failed to build tokenizers ERROR: Could not build wheels for tokenizers, which is required to install pyproject.toml-based projects WARNING: You are using pip version 22.0.4; however, version 22.1.2 is available. You should consider upgrading via the '/Users/anil/.../venv/bin/python -m pip install --upgrade pip' command. It seems I need to install rust compiler curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh verify the installation via rustc -h . I needed to close and reopen terminal again. install again pip install fastbook returns ... Using legacy 'setup.py install' for sentencepiece, since package 'wheel' is not installed. Installing collected packages: sentencepiece, murmurhash, cymem, xxhash, typing-extensions, typer, tqdm, threadpoolctl, spacy-loggers, spacy-legacy, smart-open, regex, preshed, pillow, numpy, multidict, langcodes, kiwisolver, joblib, graphviz, fsspec, frozenlist, fonttools, filelock, fastprogress, dill, cycler, catalogue, async-timeout, yarl, torch, srsly, scipy, responses, pydantic, pyarrow, pathy, pandas, multiprocess, matplotlib, huggingface-hub, fastcore, blis, aiosignal, transformers, torchvision, thinc, scikit-learn, fastdownload, aiohttp, spacy, fastai, datasets, fastbook Running setup.py install for sentencepiece ... error error: subprocess-exited-with-error \u00d7 Running setup.py install for sentencepiece did not run successfully. \u2502 exit code: 1 \u2570\u2500> [43 lines of output] ~/.pyenv/versions/3.10.5/lib/python3.10/site-packages/setuptools/dist.py:717: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead warnings.warn( running install running build running build_py creating build creating build/lib.macosx-12.1-arm64-3.10 creating build/lib.macosx-12.1-arm64-3.10/sentencepiece copying src/sentencepiece/__init__.py -> build/lib.macosx-12.1-arm64-3.10/sentencepiece copying src/sentencepiece/sentencepiece_model_pb2.py -> build/lib.macosx-12.1-arm64-3.10/sentencepiece copying src/sentencepiece/sentencepiece_pb2.py -> build/lib.macosx-12.1-arm64-3.10/sentencepiece running build_ext Package sentencepiece was not found in the pkg-config search path. Perhaps you should add the directory containing `sentencepiece.pc' to the PKG_CONFIG_PATH environment variable No package 'sentencepiece' found Cloning into 'sentencepiece'... Note: switching to 'd8711f55d9b2cb9c77a00adcc18108482b29b675'. You are in 'detached HEAD' state. You can look around, make experimental changes and commit them, and you can discard any commits you make in this state without impacting any branches by switching back to a branch. If you want to create a new branch to retain commits you create, you may do so (now or later) by using -c with the switch command. Example: git switch -c <new-branch-name> Or undo this operation with: git switch - Turn off this advice by setting config variable advice.detachedHead to false ./build_bundled.sh: line 15: cmake: command not found ./build_bundled.sh: line 16: nproc: command not found make: *** No targets specified and no makefile found. Stop. make: *** No rule to make target `install'. Stop. Package sentencepiece was not found in the pkg-config search path. Perhaps you should add the directory containing `sentencepiece.pc' to the PKG_CONFIG_PATH environment variable No package 'sentencepiece' found Failed to find sentencepiece pkg-config [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. error: legacy-install-failure \u00d7 Encountered error while trying to install package. \u2570\u2500> sentencepiece note: This is an issue with the package mentioned above, not pip. hint: See above for output from the failure. check if cmake is installed cmake -h -> zsh: command not found: cmake Install cmake brew install cmake Try again pip install fastbook It failed with following log ... ^ In file included from src/sentencepiece/sentencepiece_wrap.cxx:2808: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:642:26: error: no template named 'numeric_limits' bool _FloatBigger = (numeric_limits<_FloatT>::digits > numeric_limits<_IntT>::digits), ^ /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:642:60: error: no template named 'numeric_limits' bool _FloatBigger = (numeric_limits<_FloatT>::digits > numeric_limits<_IntT>::digits), ^ /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:643:18: error: no template named 'numeric_limits' int _Bits = (numeric_limits<_IntT>::digits - numeric_limits<_FloatT>::digits)> ^ /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:643:50: error: no template named 'numeric_limits' int _Bits = (numeric_limits<_IntT>::digits - numeric_limits<_FloatT>::digits)> ^ /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:648:17: error: no template named 'numeric_limits' static_assert(numeric_limits<_FloatT>::radix == 2, \"FloatT has incorrect radix\"); ^ /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:651:25: error: no template named 'numeric_limits' return _FloatBigger ? numeric_limits<_IntT>::max() : (numeric_limits<_IntT>::max() >> _Bits << _Bits); ^ /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:651:58: error: no template named 'numeric_limits' return _FloatBigger ? numeric_limits<_IntT>::max() : (numeric_limits<_IntT>::max() >> _Bits << _Bits); ^ /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:645:25: error: no return statement in constexpr function _LIBCPP_CONSTEXPR _IntT __max_representable_int_for_float() _NOEXCEPT { ^ /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:661:16: error: no template named 'numeric_limits' using _Lim = numeric_limits<_IntT>; ^ /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:664:12: error: use of undeclared identifier '_Lim' return _Lim::max(); ^ /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:665:21: error: use of undeclared identifier '_Lim' } else if (__r <= _Lim::lowest()) { ^ /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/cmath:666:12: error: use of undeclared identifier '_Lim' return _Lim::min(); ^ 197 warnings and 12 errors generated. error: command '/usr/bin/clang' failed with exit code 1 [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. error: legacy-install-failure \u00d7 Encountered error while trying to install package. \u2570\u2500> sentencepiece note: This is an issue with the package mentioned above, not pip. hint: See above for output from the failure. try to install sentencepiece via pip directly pip install sentencepiece Still getting the same error as above. Looks like there is no wheel for python 3.10 for mac os and it tries to build it in my local machine. There is a wheel for 3.9 so let's try that. pyenv install 3.9.13 pyenv local 3.9.13 rm -rf venv python -m venv venv source ./venv/bin/activate try again: pip install fastbook Success!! import fastbook -> error ModuleNotFoundError: No module named '_lzma' Let's try the solution as per this post: https://stackoverflow.com/a/69517932 brew install xz pyenv uninstall 3.9.13 pyenv install 3.9.13 rm -rf venv python -m venv venv source ./venv/bin/activate pip install fastbook try again import fastbook -> ... except ModuleNotFoundError: warn(\"Missing `ipywidgets` - please install it\") let's try pip install ipywidgets try again import fastbook This time got warning only ~/.../venv/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: dlopen(~/.../venv/lib/python3.9/site-packages/torchvision/image.so, 0x0006): Symbol not found: __ZN3c106detail19maybe_wrap_dim_slowExxb Referenced from: ~/.../venv/lib/python3.9/site-packages/torchvision/image.so Expected in: ~/.../venv/lib/python3.9/site-packages/torch/lib/libc10.dylib warn(f\"Failed to load image Python extension: {e}\") The notebook from git repo is working now!!","title":"Error installing fastbook"},{"location":"german_pr_application/","text":"How I applied for German PR On 2019.03.01 I came to Germany and started my employment at Zalando. By the 2021.12.01 I was eligible to apply for PR with A1 level. I referred to the Permanent settlement permit for EU Blue Card holders page on Berlin Service Portal to prepare the documents. Sent an email to Landesmt on 2022.03.20 To: E3@lea.berlin.de Subject: Application for Niederlassungserlaubnis Sehr geehrte Damen und Herren, Mein Name ist {FULL NAME AS PER PASSPORT} und ich bin seit M\u00e4rz 2019 in Berlin. Ich habe eine Blaue Karte, die am {DD.MM.YYYY} abl\u00e4uft. Ich arbeite als Senior Software Engineer bei der Zalando SE und habe einen unbefristeten Arbeitsvertrag. Hiermit beantrage ich die Niederlassungserlaubnis. Die erforderlichen Unterlagen finden Sie im Anhang. 1. Reisepass und Blaue Karte 2. Biometrisches Foto 3.1. Arbeitsvertrag 3.2. Arbeitgeberbescheinigung 3.3. Gehaltsabrechnungen der letzten 6 Monate 4. Wohnungsmietvertrag 5. Rentenauskunft (Altersrente) 6. Krankenversicherungskarte (TK-Karte). 7. Anmeldung 8. Zertifikat Deutsch A2 - KERN Lassen Sie es mich wissen, wenn Sie weitere Informationen ben\u00f6tigen. Mit freundlichen Gr\u00fc\u00dfe, Anil Bharadia Details about the attachments: 1. Reisepass und Blaue Karte A single PDF containing the scan copies of: my current passport, my expired passport (which is mentioned in my blue card), my blue card front and back page, zusatsblatt that I received with my blue card 2. Biometrisches Foto I a took photo in my mobile and printed on a photopaper at home. I kept the paper copy for the appointment and sent the same photo's soft copy in email. 3.1. Arbeitsvertrag Employment contract 3.2. Arbeitgeberbescheinigung I donwloaded this from Zalando's employee portal 3.3. Gehaltsabrechnungen der letzten 6 Monate Payslips of last 6 months 4. Wohnungsmietvertrag Apartment rental contract 5. Rentenauskunft (Altersrente) Pension statement that I dowloaded from the AusweisApp2 - TODO: Explain how to get this 6. Krankenversicherungskarte (TK-Karte) Scan copy of my TK card (front and back in a single PDF file) 7. Anmeldung The Anmeldebest\u00e4tigung I got from B\u00fcrgeramt 8. Zertifikat Deutsch A2 - KERN I attended the German language courses provided by Zalando via KERN. So I asked the person from KERN (who enrolled me earlier) to send me the certificate of participation. Got a reply from Landesamt on 2022.04.13 Sehr geehrter Herr Bharadia, anbei die Vorladung f\u00fcr die voraussichtliche Erteilung der Niederlassungserlaubnis am 05.05.2022. Die mitzubringenden Unterlagen k\u00f6nnen Sie dem beigef\u00fcgtem Schreiben entnehmen. Mit freundlichen Gr\u00fc\u00dfen Im Auftrag xxx The attachment in this email was a PDF file with the following information: Date and time of the appointment The address of the appointment ( Friedrich-Krause-Ufer 24, 13353 Berlin ) The name of the waiting room and the Waitingnumber A list of docuemtns to bring Translation I would ask you to bring the following documents with you (please also note the following page): - Passport - Employer's confirmation of an ongoing employment relationship (not older than 14 days) and proof of net earnings from 03/2022 - Current membership certificate of your health insurance - Registration certificate - A current biometric passport photo (35mm x 45mm, frontal photo with a neutral facial expression and closed mouth looking straight into the camera, light background) - Fee 113.00 EUR Visited the Landesamt on 2022.05.05 So I went to the landesamt with the following documents Passport (in my case the current and the expired one) Arbeitgeberbescheinigung I downloaded a new Arbeitgeberbescheinigung from Zalado's internal portal as it was more than 14 days since I sent it in the email. Confirmation about the insurance cover with TK Downloaded it from TK's website Anmeldung Photo At the gate of the Landesamt, I showed the appointment PDF I got from the email mentioned above, to the security person to get into the building. Went to the waiting room mentioned in the PDF. There were TV screens shwing the waiting nummer. When my number came I went to the mentioned room. There was a young lady who asked me to give her the documents. I handed the documents as mentioned above. Then she asked me the following questions in German. - What is your birth date? - Do you have siblings? - What are your hobbies ? Then she asked me to go to the waiting room again, and come back when my waiting nummber apper on the TV. She kept the douments with her. I went to waiting room and after 5-10 minutes my number appeared again so I went there again. This time she asked me to sign on the tablet and asked me two more questions: - What is your height? - What is your eye color? Then she printed and gave me a confirmation letter. And told me that I will get the electronic permit (card) by 4 to 6 weeks. And then she returned me all my documents and gave me a card to pay the fee. If you are new to this: It is like a credit card. That you can enter into the payment machine, the machine will take it and ask to pay via your bank card. I went to waiting room again where there was the payment machine, there I paid the fee. The confirmation letter I got from this visit mentioned this: The production of the card can take a few weeks, so that the electronic residence permit cannot be expected to be sent before June 16, 2022. Got the Residence Permit on 2022.06.09 Got a letter with PIN on 2022.05.28 Got the PR card on 2022.06.09 Activated the OnlineID Function of the Resident Permit Checked if my card is activated for the online ID function via AusweisApp2 android app. So this confirms that online ID feature of my card is disabled. Hence I tried to activate it. I found here that there is anther way to activate, which is to visit B\u00fcrgeramt. I booked an appointment via the Online-Ausweisfunktion (eID) - nachtr\u00e4glich aktivieren page on Berlin Service Portal I went to the B\u00fcrgeramt. The person from Burgeramt asked me if I received the card via mail. She said the cards sent via mail are not activated for online id function. Also she informed that she cannot activate the card, she can only reset the PIN. To activate I need to send and email to landesamt. I need to look at the letter that came along with the card, on that letter on the top right corner there will be the email id which I should send an email to. (When I looked at that letter, it is also mentioned there that the OnlineId function is not activated. \ud83e\udd26\u200d\u2642\ufe0f) So I sent an email to the Landesamt. Subject: Antrag auf Aktivierung der Online-Ausweisfunktion f\u00fcr den elektronischen Aufenthaltstitel Gesch\u00e4ftszeichen: {file number mentioned in the letter in the top right corner} Sehr geehrter Herr {name of the person}, Mein Name ist Anil Bharadia (geboren am {DD.MM.YYYY}). Ich habe k\u00fcrzlich den elektronischen Aufenthaltstitel mit deaktivierter Online-Ausweisfunktion erhalten. Ich habe versucht, den Aktivierungsbrief online zu bestellen, aber ich erhalte eine Meldung, dass meine Karte nicht unterst\u00fctzt wird. Bitte sehen Sie sich den Screenshot unten an. {image.png} Ich habe daf\u00fcr auch ein B\u00fcrgeramt aufgesucht, und die Antwort von dort war, Ihnen eine E-Mail zu schicken. K\u00f6nnen Sie mir bitte helfen, die Online-Ausweisfunktion zu aktivieren? Ich freue mich auf deine Antwort. Mit freundlichen Gr\u00fc\u00dfe, Anil Bharadia I got a reply next day morning: Sehr geehrter Herr Bharadia, ich habe Ihnen gerade einen Termin gebucht. Bitte schauen Sie in Ihrem Email Postfach nach. Mit freundlichen Gr\u00fc\u00dfen Im Auftrag Herr {name} There was an email for Termin (2 months in future) with the following information: Voraussetzungen / Erforderliche Unterlagen: - Bestellung des eAT ist erfolgt Ein Antrag auf Erteilung eines Aufenthaltstitels (Aufenthaltserlaubnis, Blaue Karte EU, Niederlassungserlaubnis oder Erlaubnis zum Daueraufenthalt-EU) muss positiv entschieden und der eAT bei der Bundesdruckerei bestellt worden sein. - Pers\u00f6nliche Abholung oder durch eine bevollm\u00e4chtigte Person - Pass oder Passersatz - Bisheriger eAT Soweit vorhanden, ist der eAT zum bisherigen Aufenthaltstitel mitzubringen. - Vollmacht und Pass / Personalausweis des oder der Bevollm\u00e4chtigten Der eAT kann durch eine bevollm\u00e4chtigte Person abgeholt werden. Kosten: keine I will update after this visit.","title":"How I applied for German PR"},{"location":"german_pr_application/#how-i-applied-for-german-pr","text":"On 2019.03.01 I came to Germany and started my employment at Zalando. By the 2021.12.01 I was eligible to apply for PR with A1 level. I referred to the Permanent settlement permit for EU Blue Card holders page on Berlin Service Portal to prepare the documents.","title":"How I applied for German PR"},{"location":"german_pr_application/#sent-an-email-to-landesmt-on-20220320","text":"To: E3@lea.berlin.de Subject: Application for Niederlassungserlaubnis Sehr geehrte Damen und Herren, Mein Name ist {FULL NAME AS PER PASSPORT} und ich bin seit M\u00e4rz 2019 in Berlin. Ich habe eine Blaue Karte, die am {DD.MM.YYYY} abl\u00e4uft. Ich arbeite als Senior Software Engineer bei der Zalando SE und habe einen unbefristeten Arbeitsvertrag. Hiermit beantrage ich die Niederlassungserlaubnis. Die erforderlichen Unterlagen finden Sie im Anhang. 1. Reisepass und Blaue Karte 2. Biometrisches Foto 3.1. Arbeitsvertrag 3.2. Arbeitgeberbescheinigung 3.3. Gehaltsabrechnungen der letzten 6 Monate 4. Wohnungsmietvertrag 5. Rentenauskunft (Altersrente) 6. Krankenversicherungskarte (TK-Karte). 7. Anmeldung 8. Zertifikat Deutsch A2 - KERN Lassen Sie es mich wissen, wenn Sie weitere Informationen ben\u00f6tigen. Mit freundlichen Gr\u00fc\u00dfe, Anil Bharadia Details about the attachments: 1. Reisepass und Blaue Karte A single PDF containing the scan copies of: my current passport, my expired passport (which is mentioned in my blue card), my blue card front and back page, zusatsblatt that I received with my blue card 2. Biometrisches Foto I a took photo in my mobile and printed on a photopaper at home. I kept the paper copy for the appointment and sent the same photo's soft copy in email. 3.1. Arbeitsvertrag Employment contract 3.2. Arbeitgeberbescheinigung I donwloaded this from Zalando's employee portal 3.3. Gehaltsabrechnungen der letzten 6 Monate Payslips of last 6 months 4. Wohnungsmietvertrag Apartment rental contract 5. Rentenauskunft (Altersrente) Pension statement that I dowloaded from the AusweisApp2 - TODO: Explain how to get this 6. Krankenversicherungskarte (TK-Karte) Scan copy of my TK card (front and back in a single PDF file) 7. Anmeldung The Anmeldebest\u00e4tigung I got from B\u00fcrgeramt 8. Zertifikat Deutsch A2 - KERN I attended the German language courses provided by Zalando via KERN. So I asked the person from KERN (who enrolled me earlier) to send me the certificate of participation.","title":"Sent an email to Landesmt on 2022.03.20"},{"location":"german_pr_application/#got-a-reply-from-landesamt-on-20220413","text":"Sehr geehrter Herr Bharadia, anbei die Vorladung f\u00fcr die voraussichtliche Erteilung der Niederlassungserlaubnis am 05.05.2022. Die mitzubringenden Unterlagen k\u00f6nnen Sie dem beigef\u00fcgtem Schreiben entnehmen. Mit freundlichen Gr\u00fc\u00dfen Im Auftrag xxx The attachment in this email was a PDF file with the following information: Date and time of the appointment The address of the appointment ( Friedrich-Krause-Ufer 24, 13353 Berlin ) The name of the waiting room and the Waitingnumber A list of docuemtns to bring Translation I would ask you to bring the following documents with you (please also note the following page): - Passport - Employer's confirmation of an ongoing employment relationship (not older than 14 days) and proof of net earnings from 03/2022 - Current membership certificate of your health insurance - Registration certificate - A current biometric passport photo (35mm x 45mm, frontal photo with a neutral facial expression and closed mouth looking straight into the camera, light background) - Fee 113.00 EUR","title":"Got a reply from Landesamt on 2022.04.13"},{"location":"german_pr_application/#visited-the-landesamt-on-20220505","text":"So I went to the landesamt with the following documents Passport (in my case the current and the expired one) Arbeitgeberbescheinigung I downloaded a new Arbeitgeberbescheinigung from Zalado's internal portal as it was more than 14 days since I sent it in the email. Confirmation about the insurance cover with TK Downloaded it from TK's website Anmeldung Photo At the gate of the Landesamt, I showed the appointment PDF I got from the email mentioned above, to the security person to get into the building. Went to the waiting room mentioned in the PDF. There were TV screens shwing the waiting nummer. When my number came I went to the mentioned room. There was a young lady who asked me to give her the documents. I handed the documents as mentioned above. Then she asked me the following questions in German. - What is your birth date? - Do you have siblings? - What are your hobbies ? Then she asked me to go to the waiting room again, and come back when my waiting nummber apper on the TV. She kept the douments with her. I went to waiting room and after 5-10 minutes my number appeared again so I went there again. This time she asked me to sign on the tablet and asked me two more questions: - What is your height? - What is your eye color? Then she printed and gave me a confirmation letter. And told me that I will get the electronic permit (card) by 4 to 6 weeks. And then she returned me all my documents and gave me a card to pay the fee. If you are new to this: It is like a credit card. That you can enter into the payment machine, the machine will take it and ask to pay via your bank card. I went to waiting room again where there was the payment machine, there I paid the fee. The confirmation letter I got from this visit mentioned this: The production of the card can take a few weeks, so that the electronic residence permit cannot be expected to be sent before June 16, 2022.","title":"Visited the Landesamt on 2022.05.05"},{"location":"german_pr_application/#got-the-residence-permit-on-20220609","text":"Got a letter with PIN on 2022.05.28 Got the PR card on 2022.06.09","title":"Got the Residence Permit on 2022.06.09"},{"location":"german_pr_application/#activated-the-onlineid-function-of-the-resident-permit","text":"Checked if my card is activated for the online ID function via AusweisApp2 android app. So this confirms that online ID feature of my card is disabled. Hence I tried to activate it. I found here that there is anther way to activate, which is to visit B\u00fcrgeramt. I booked an appointment via the Online-Ausweisfunktion (eID) - nachtr\u00e4glich aktivieren page on Berlin Service Portal I went to the B\u00fcrgeramt. The person from Burgeramt asked me if I received the card via mail. She said the cards sent via mail are not activated for online id function. Also she informed that she cannot activate the card, she can only reset the PIN. To activate I need to send and email to landesamt. I need to look at the letter that came along with the card, on that letter on the top right corner there will be the email id which I should send an email to. (When I looked at that letter, it is also mentioned there that the OnlineId function is not activated. \ud83e\udd26\u200d\u2642\ufe0f) So I sent an email to the Landesamt. Subject: Antrag auf Aktivierung der Online-Ausweisfunktion f\u00fcr den elektronischen Aufenthaltstitel Gesch\u00e4ftszeichen: {file number mentioned in the letter in the top right corner} Sehr geehrter Herr {name of the person}, Mein Name ist Anil Bharadia (geboren am {DD.MM.YYYY}). Ich habe k\u00fcrzlich den elektronischen Aufenthaltstitel mit deaktivierter Online-Ausweisfunktion erhalten. Ich habe versucht, den Aktivierungsbrief online zu bestellen, aber ich erhalte eine Meldung, dass meine Karte nicht unterst\u00fctzt wird. Bitte sehen Sie sich den Screenshot unten an. {image.png} Ich habe daf\u00fcr auch ein B\u00fcrgeramt aufgesucht, und die Antwort von dort war, Ihnen eine E-Mail zu schicken. K\u00f6nnen Sie mir bitte helfen, die Online-Ausweisfunktion zu aktivieren? Ich freue mich auf deine Antwort. Mit freundlichen Gr\u00fc\u00dfe, Anil Bharadia I got a reply next day morning: Sehr geehrter Herr Bharadia, ich habe Ihnen gerade einen Termin gebucht. Bitte schauen Sie in Ihrem Email Postfach nach. Mit freundlichen Gr\u00fc\u00dfen Im Auftrag Herr {name} There was an email for Termin (2 months in future) with the following information: Voraussetzungen / Erforderliche Unterlagen: - Bestellung des eAT ist erfolgt Ein Antrag auf Erteilung eines Aufenthaltstitels (Aufenthaltserlaubnis, Blaue Karte EU, Niederlassungserlaubnis oder Erlaubnis zum Daueraufenthalt-EU) muss positiv entschieden und der eAT bei der Bundesdruckerei bestellt worden sein. - Pers\u00f6nliche Abholung oder durch eine bevollm\u00e4chtigte Person - Pass oder Passersatz - Bisheriger eAT Soweit vorhanden, ist der eAT zum bisherigen Aufenthaltstitel mitzubringen. - Vollmacht und Pass / Personalausweis des oder der Bevollm\u00e4chtigten Der eAT kann durch eine bevollm\u00e4chtigte Person abgeholt werden. Kosten: keine I will update after this visit.","title":"Activated the OnlineID Function of the Resident Permit"},{"location":"git/","text":"Change Git user for a repository git config user.name \"anilbhradia\" git config user.email \"anil.bharadia@gmail.com\" Use Github token Open nano .git/config Replace the following line [remote \"origin\"] url = https://github.com/anilbharadia/anilbharadia.github.io.git With [remote \"origin\"] url = https://xxx@github.com/anilbharadia/anilbharadia.github.io.git Where xxx is the token Use atom as a git editor git config --global core.editor \"atom --wait\" git change the user of a commit Ref: https://stackoverflow.com/a/3042512 git rebase -i HEAD~1 This opened editor (atom) with content pick 049c296 update instructions for local env setup in README.md # ... Changed pick to edit , saved, and closed atom. git commit --amend --author=\"Author Name <email@address.com>\" It opened editor again to set the commit message. Updated message, saved, and closed atom. git rebase --continue git push -f done.","title":"Git"},{"location":"git/#change-git-user-for-a-repository","text":"git config user.name \"anilbhradia\" git config user.email \"anil.bharadia@gmail.com\"","title":"Change Git user for a repository"},{"location":"git/#use-github-token","text":"Open nano .git/config Replace the following line [remote \"origin\"] url = https://github.com/anilbharadia/anilbharadia.github.io.git With [remote \"origin\"] url = https://xxx@github.com/anilbharadia/anilbharadia.github.io.git Where xxx is the token","title":"Use Github token"},{"location":"git/#use-atom-as-a-git-editor","text":"git config --global core.editor \"atom --wait\"","title":"Use atom as a git editor"},{"location":"git/#git-change-the-user-of-a-commit","text":"Ref: https://stackoverflow.com/a/3042512 git rebase -i HEAD~1 This opened editor (atom) with content pick 049c296 update instructions for local env setup in README.md # ... Changed pick to edit , saved, and closed atom. git commit --amend --author=\"Author Name <email@address.com>\" It opened editor again to set the commit message. Updated message, saved, and closed atom. git rebase --continue git push -f done.","title":"git change the user of a commit"},{"location":"gpg_key/","text":"GPG Key check if gpg is installed gpg -h -> zsh: command not found: gpg not installed. Install GPG brew install gnupg Import private key If you have it generared it in another machine. gpg --import ~/Downloads/Secret.asc Find the key id gpg --list-keys This prints following /Users/abharadia/.gnupg/pubring.kbx ----------------------------------- pub rsa4096 2022-06-18 [SC] [expires: 2026-06-18] ACACACACACACAC1111111111QQQQZZZZABCDEFGH uid [ unknown] username <user.name@gmail.com> sub rsa4096 2022-06-18 [E] [expires: 2026-06-18] Here the last 8 characters ABCDEFGH is the key id Create a secring file This can be used to sign the artifacts before publishing to maven repo. gpg --keyring secring.gpg --export-secret-key ABCDEFGH > secring.gpg returns gpg: keyblock resource '/Users/abharadia/.gnupg/secring.gpg': No such file or directory gpg --export-secret-key ABCDEFGH > secring.gpg This worked TODO How to generate GPG key to sign maven packages before publishing to maven central repo","title":"GPG Key"},{"location":"gpg_key/#gpg-key","text":"check if gpg is installed gpg -h -> zsh: command not found: gpg not installed.","title":"GPG Key"},{"location":"gpg_key/#install-gpg","text":"brew install gnupg","title":"Install GPG"},{"location":"gpg_key/#import-private-key","text":"If you have it generared it in another machine. gpg --import ~/Downloads/Secret.asc","title":"Import private key"},{"location":"gpg_key/#find-the-key-id","text":"gpg --list-keys This prints following /Users/abharadia/.gnupg/pubring.kbx ----------------------------------- pub rsa4096 2022-06-18 [SC] [expires: 2026-06-18] ACACACACACACAC1111111111QQQQZZZZABCDEFGH uid [ unknown] username <user.name@gmail.com> sub rsa4096 2022-06-18 [E] [expires: 2026-06-18] Here the last 8 characters ABCDEFGH is the key id","title":"Find the key id"},{"location":"gpg_key/#create-a-secring-file","text":"This can be used to sign the artifacts before publishing to maven repo. gpg --keyring secring.gpg --export-secret-key ABCDEFGH > secring.gpg returns gpg: keyblock resource '/Users/abharadia/.gnupg/secring.gpg': No such file or directory gpg --export-secret-key ABCDEFGH > secring.gpg This worked","title":"Create a secring file"},{"location":"gpg_key/#todo","text":"How to generate GPG key to sign maven packages before publishing to maven central repo","title":"TODO"},{"location":"install_python/","text":"Install pyenv curl https://pyenv.run | bash Verify pyenv is installed pyenv versions --> zsh: command not found: pyenv This erorr is because I need to configure the shell env Set shell env ref: https://github.com/pyenv/pyenv#set-up-your-shell-environment-for-pyenv echo 'export PYENV_ROOT=\"$HOME/.pyenv\"' >> ~/.zshrc echo 'command -v pyenv >/dev/null || export PATH=\"$PYENV_ROOT/bin:$PATH\"' >> ~/.zshrc echo 'eval \"$(pyenv init -)\"' >> ~/.zshrc source ~/.zshrc pyenv versions --> * system (set by /Users/abharadia/.pyenv/version) install python pyenv install 3.10.5 pyenv versions --> * system (set by /Users/abharadia/.pyenv/version) 3.10.5 set python version python --version --> Python 2.7.18 My python command is still set to use older version pyenv global 3.10.5 python --version --> Python 2.7.18 pyenv versions --> system * 3.10.5 (set by /Users/abharadia/.pyenv/version) So the * moved to the 3.10.5 but it is not used by python --version yet In the file ~/.zshrc change line eval \"$(pyenv init -)\" to eval \"$(pyenv init --path)\" Ref: https://stackoverflow.com/a/68228627 source ~/.zshrc python --version --> Python 3.10.5 Install poetry curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python - source $HOME/.poetry/env poetry --version --> Poetry version 1.1.13","title":"Install python"},{"location":"install_python/#install-pyenv","text":"curl https://pyenv.run | bash","title":"Install pyenv"},{"location":"install_python/#verify-pyenv-is-installed","text":"pyenv versions --> zsh: command not found: pyenv This erorr is because I need to configure the shell env","title":"Verify pyenv is installed"},{"location":"install_python/#set-shell-env","text":"ref: https://github.com/pyenv/pyenv#set-up-your-shell-environment-for-pyenv echo 'export PYENV_ROOT=\"$HOME/.pyenv\"' >> ~/.zshrc echo 'command -v pyenv >/dev/null || export PATH=\"$PYENV_ROOT/bin:$PATH\"' >> ~/.zshrc echo 'eval \"$(pyenv init -)\"' >> ~/.zshrc source ~/.zshrc pyenv versions --> * system (set by /Users/abharadia/.pyenv/version)","title":"Set shell env"},{"location":"install_python/#install-python","text":"pyenv install 3.10.5 pyenv versions --> * system (set by /Users/abharadia/.pyenv/version) 3.10.5","title":"install python"},{"location":"install_python/#set-python-version","text":"python --version --> Python 2.7.18 My python command is still set to use older version pyenv global 3.10.5 python --version --> Python 2.7.18 pyenv versions --> system * 3.10.5 (set by /Users/abharadia/.pyenv/version) So the * moved to the 3.10.5 but it is not used by python --version yet In the file ~/.zshrc change line eval \"$(pyenv init -)\" to eval \"$(pyenv init --path)\" Ref: https://stackoverflow.com/a/68228627 source ~/.zshrc python --version --> Python 3.10.5","title":"set python version"},{"location":"install_python/#install-poetry","text":"curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python - source $HOME/.poetry/env poetry --version --> Poetry version 1.1.13","title":"Install poetry"},{"location":"intellij_idea/","text":"IDEA Shortcuts Idea - Navigate through the changes in the file idea move to the next change \u2303 \u2325 \u21e7 \u2193 or \u2303 \u2325 \u21e7 \u2191","title":"IDEA Shortcuts"},{"location":"intellij_idea/#idea-shortcuts","text":"","title":"IDEA Shortcuts"},{"location":"intellij_idea/#idea-navigate-through-the-changes-in-the-file","text":"idea move to the next change \u2303 \u2325 \u21e7 \u2193 or \u2303 \u2325 \u21e7 \u2191","title":"Idea - Navigate through the changes in the file"},{"location":"java_create_a_schduler_thread_do_repeatative_task/","text":"Java create a new thread to do repeatative task","title":"Java create a new thread to do repeatative task"},{"location":"java_create_a_schduler_thread_do_repeatative_task/#java-create-a-new-thread-to-do-repeatative-task","text":"","title":"Java create a new thread to do repeatative task"},{"location":"java_make_a_fat_jar_with_dependencies/","text":"Java make a fat jar with dependencies using gradle Modify the jar gradle task to copy dependencies files tasks.jar { manifest.attributes[\"Main-Class\"] = \"org.package.AppKt\" from(configurations.runtimeClasspath.get().map { if (it.isDirectory) it else zipTree(it) }) } Try again: $ ./gradlew clean build > Task :compileKotlin 'compileJava' task (current target is 18) and 'compileKotlin' task (current target is 1.8) jvm target compatibility should be set to the same Java version. > Task :jar FAILED FAILURE: Build failed with an exception. * What went wrong: Execution failed for task ':jar'. > Entry META-INF/versions/9/module-info.class is a duplicate but no duplicate handling strategy has been set. Please refer to https://docs.gradle.org/7.4.2/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:duplicatesStrategy for details. * Try: > Run with --stacktrace option to get the stack trace. > Run with --info or --debug option to get more log output. > Run with --scan to get full insights. * Get more help at https://help.gradle.org Add duplicate strategy as suggested by gradle tasks.jar { ... from(configurations.runtimeClasspath.get().map { if (it.isDirectory) it else zipTree(it) }) duplicatesStrategy = DuplicatesStrategy.EXCLUDE } Try again $ ./gradlew clean build > Task :compileKotlin 'compileJava' task (current target is 18) and 'compileKotlin' task (current target is 1.8) jvm target compatibility should be set to the same Java version. BUILD SUCCESSFUL in 6s ref: - https://www.baeldung.com/gradle-fat-jar - https://stackoverflow.com/a/43998029","title":"Java make a fat jar with dependencies using gradle"},{"location":"java_make_a_fat_jar_with_dependencies/#java-make-a-fat-jar-with-dependencies-using-gradle","text":"Modify the jar gradle task to copy dependencies files tasks.jar { manifest.attributes[\"Main-Class\"] = \"org.package.AppKt\" from(configurations.runtimeClasspath.get().map { if (it.isDirectory) it else zipTree(it) }) } Try again: $ ./gradlew clean build > Task :compileKotlin 'compileJava' task (current target is 18) and 'compileKotlin' task (current target is 1.8) jvm target compatibility should be set to the same Java version. > Task :jar FAILED FAILURE: Build failed with an exception. * What went wrong: Execution failed for task ':jar'. > Entry META-INF/versions/9/module-info.class is a duplicate but no duplicate handling strategy has been set. Please refer to https://docs.gradle.org/7.4.2/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:duplicatesStrategy for details. * Try: > Run with --stacktrace option to get the stack trace. > Run with --info or --debug option to get more log output. > Run with --scan to get full insights. * Get more help at https://help.gradle.org Add duplicate strategy as suggested by gradle tasks.jar { ... from(configurations.runtimeClasspath.get().map { if (it.isDirectory) it else zipTree(it) }) duplicatesStrategy = DuplicatesStrategy.EXCLUDE } Try again $ ./gradlew clean build > Task :compileKotlin 'compileJava' task (current target is 18) and 'compileKotlin' task (current target is 1.8) jvm target compatibility should be set to the same Java version. BUILD SUCCESSFUL in 6s ref: - https://www.baeldung.com/gradle-fat-jar - https://stackoverflow.com/a/43998029","title":"Java make a fat jar with dependencies using gradle"},{"location":"java_no_main_manifest_attribute_in_jar/","text":"Java no main manifest attribute, in MyApp.jar $ java -jar ./build/libs/MyApp.jar no main manifest attribute, in ./build/libs/MyApp.jar In build.gradle.kts file add: tasks.jar { manifest.attributes[\"Main-Class\"] = \"org.package.AppKt\" }","title":"Java no main manifest attribute, in MyApp.jar"},{"location":"java_no_main_manifest_attribute_in_jar/#java-no-main-manifest-attribute-in-myappjar","text":"$ java -jar ./build/libs/MyApp.jar no main manifest attribute, in ./build/libs/MyApp.jar In build.gradle.kts file add: tasks.jar { manifest.attributes[\"Main-Class\"] = \"org.package.AppKt\" }","title":"Java no main manifest attribute, in MyApp.jar"},{"location":"java_write_milliseconds_in_readable_way/","text":"Java write milliseconds in a readable way While writing java code where let's say I need to pass an argument which takes milliseconds. example: import java.util.Timer Timer(\"refresher\", true).schedule(refresh(), 300000) I find that confusing about what does 300000 mean. I know it is millis but it doesn't click immediately what duration it represents. One alternative is Timer(\"refresher\", true).schedule(refresh(), 1000*60*5) This give a hint that it is 5 minutes. However, it still puts a small cognitive load. A better alternative is import java.util.concurrent.TimeUnit Timer(\"refresher\", true).schedule(refresh(), TimeUnit.MINUTES.toMillis(5))","title":"Java write milliseconds in a readable way"},{"location":"java_write_milliseconds_in_readable_way/#java-write-milliseconds-in-a-readable-way","text":"While writing java code where let's say I need to pass an argument which takes milliseconds. example: import java.util.Timer Timer(\"refresher\", true).schedule(refresh(), 300000) I find that confusing about what does 300000 mean. I know it is millis but it doesn't click immediately what duration it represents. One alternative is Timer(\"refresher\", true).schedule(refresh(), 1000*60*5) This give a hint that it is 5 minutes. However, it still puts a small cognitive load. A better alternative is import java.util.concurrent.TimeUnit Timer(\"refresher\", true).schedule(refresh(), TimeUnit.MINUTES.toMillis(5))","title":"Java write milliseconds in a readable way"},{"location":"mac_disable_ctrl_space_input_language_selection/","text":"When I press ctrl + space while writing code, instead of showing the auto-complete drop down it shows the dropdown to change the language. This apple support page also states that this is a shortcut to switch language: Open system preferences \uf8ff \u2192 System Preferences... Select Language & Region Click on Keyboard Preferences... button Select Shortcuts tab Select Input Sources from the list shown in left side Deselect (or change) the following checkboxes [ ] Select the previous input source \u2303Space [ ] Select next source in input menu \u2303\u2325Space ref: https://www.webnots.com/keyboard-shortcut-to-switch-language-in-mac-and-windows-10/","title":"Mac disable ctrl space input language selection"},{"location":"mac_open_file_dialog_show_hidden_files/","text":"Mac - open files dialog show hidden files It is not showing the hidden files for example .env Solution: \u2318 \u21e7 .","title":"Mac - open files dialog show hidden files"},{"location":"mac_open_file_dialog_show_hidden_files/#mac-open-files-dialog-show-hidden-files","text":"It is not showing the hidden files for example .env Solution: \u2318 \u21e7 .","title":"Mac - open files dialog show hidden files"},{"location":"mac_shortcuts/","text":"Mac Shortcuts copy file content to clipboard pbcopy < file.txt or cat file.txt | pbcopy Key Symbols \u21e7 \u2303 \u2325 \u2318 \u232b \u23ce \u2191 \u2193 \u2190 \u2192 \uf8ff Show hidden files \u2318 \u21e7 . mac - enable function keys by default ref: https://support.feralinteractive.com/en/faqs/fkeys/ Open System Preferences ( \uf8ff \u2192 System Preferences... ). Select Keyboard (or Keyboard and Mouse depending on the version of Mac OS X you are running). Select the Keyboard tab. Check the checkbox Use F1, F2, etc. keys as standard function keys","title":"Mac Shortcuts"},{"location":"mac_shortcuts/#mac-shortcuts","text":"","title":"Mac Shortcuts"},{"location":"mac_shortcuts/#copy-file-content-to-clipboard","text":"pbcopy < file.txt or cat file.txt | pbcopy","title":"copy file content to clipboard"},{"location":"mac_shortcuts/#key-symbols","text":"\u21e7 \u2303 \u2325 \u2318 \u232b \u23ce \u2191 \u2193 \u2190 \u2192 \uf8ff","title":"Key Symbols"},{"location":"mac_shortcuts/#show-hidden-files","text":"\u2318 \u21e7 .","title":"Show hidden files"},{"location":"mac_shortcuts/#mac-enable-function-keys-by-default","text":"ref: https://support.feralinteractive.com/en/faqs/fkeys/ Open System Preferences ( \uf8ff \u2192 System Preferences... ). Select Keyboard (or Keyboard and Mouse depending on the version of Mac OS X you are running). Select the Keyboard tab. Check the checkbox Use F1, F2, etc. keys as standard function keys","title":"mac - enable function keys by default"},{"location":"maven_publish_to_central_repo/","text":"ref: https://madhead.me/posts/no-bullshit-maven-publish/","title":"Maven publish to central repo"},{"location":"maven_settings_xml_file_missing/","text":"Maven settings.xml file is missing It is not created by default, you need to create it manually. ( ref ) sample: <settings xmlns=\"http://maven.apache.org/SETTINGS/1.0.0\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd\"> <localRepository/> <interactiveMode/> <offline/> <pluginGroups/> <servers/> <mirrors/> <proxies/> <profiles/> <activeProfiles/> </settings>","title":"Maven settings.xml file is missing"},{"location":"maven_settings_xml_file_missing/#maven-settingsxml-file-is-missing","text":"It is not created by default, you need to create it manually. ( ref ) sample: <settings xmlns=\"http://maven.apache.org/SETTINGS/1.0.0\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd\"> <localRepository/> <interactiveMode/> <offline/> <pluginGroups/> <servers/> <mirrors/> <proxies/> <profiles/> <activeProfiles/> </settings>","title":"Maven settings.xml file is missing"},{"location":"mkdocs_serve_another_port/","text":"mkdocs serve use another different port $ mkdocs serve INFO - Building documentation... INFO - Cleaning site directory INFO - Documentation built in 0.62 seconds OSError: [Errno 48] Address already in use $ mkdocs serve -a localhost:9000 worked!","title":"mkdocs serve use another different port"},{"location":"mkdocs_serve_another_port/#mkdocs-serve-use-another-different-port","text":"$ mkdocs serve INFO - Building documentation... INFO - Cleaning site directory INFO - Documentation built in 0.62 seconds OSError: [Errno 48] Address already in use $ mkdocs serve -a localhost:9000 worked!","title":"mkdocs serve use another different port"},{"location":"python_create_venv/","text":"create a new venv python -m venv venv creates a directory venv in current directory activate it source ./venv/bin/activate","title":"Python create venv"},{"location":"python_create_venv/#create-a-new-venv","text":"python -m venv venv creates a directory venv in current directory","title":"create a new venv"},{"location":"python_create_venv/#activate-it","text":"source ./venv/bin/activate","title":"activate it"},{"location":"python_package_find_latest_version/","text":"'","title":"Python package find latest version"},{"location":"python_poetry_black_no_such_file/","text":"Problem poetry run black Returns FileNotFoundError [Errno 2] No such file or directory: b'~/.local/bin/black' at ~/.pyenv/versions/3.10.5/lib/python3.10/os.py:607 in _execvpe 603\u2502 path_list = map(fsencode, path_list) 604\u2502 for dir in path_list: 605\u2502 fullname = path.join(dir, file) 606\u2502 try: \u2192 607\u2502 exec_func(fullname, *argrest) 608\u2502 except (FileNotFoundError, NotADirectoryError) as e: 609\u2502 last_exc = e 610\u2502 except OSError as e: 611\u2502 last_exc = e Solution make sure poetry installed properly. run poetry install --> it failed with \u2022 Installing typed-ast (1.4.3) EnvCommandError ... 199 warnings and 1 error generated. error: command '/usr/bin/clang' failed with exit code 1 [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. error: legacy-install-failure \u00d7 Encountered error while trying to install package. \u2570\u2500> typed-ast note: This is an issue with the package mentioned above, not pip. hint: See above for output from the failure. at ~/.poetry/lib/poetry/utils/env.py:1195 in _run 1191\u2502 output = subprocess.check_output( 1192\u2502 cmd, stderr=subprocess.STDOUT, **kwargs 1193\u2502 ) 1194\u2502 except CalledProcessError as e: \u2192 1195\u2502 raise EnvCommandError(e, input=input_) 1196\u2502 1197\u2502 return decode(output) 1198\u2502 1199\u2502 def execute(self, bin, *args, **kwargs): This error is while installing Installing typed-ast (1.4.3) This package was a dependency of mypy (0.761). I changed the mypy version to 0.961 and it does not have this dependency.","title":"Python poetry black no such file"},{"location":"python_poetry_black_no_such_file/#problem","text":"poetry run black Returns FileNotFoundError [Errno 2] No such file or directory: b'~/.local/bin/black' at ~/.pyenv/versions/3.10.5/lib/python3.10/os.py:607 in _execvpe 603\u2502 path_list = map(fsencode, path_list) 604\u2502 for dir in path_list: 605\u2502 fullname = path.join(dir, file) 606\u2502 try: \u2192 607\u2502 exec_func(fullname, *argrest) 608\u2502 except (FileNotFoundError, NotADirectoryError) as e: 609\u2502 last_exc = e 610\u2502 except OSError as e: 611\u2502 last_exc = e","title":"Problem"},{"location":"python_poetry_black_no_such_file/#solution","text":"make sure poetry installed properly. run poetry install --> it failed with \u2022 Installing typed-ast (1.4.3) EnvCommandError ... 199 warnings and 1 error generated. error: command '/usr/bin/clang' failed with exit code 1 [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. error: legacy-install-failure \u00d7 Encountered error while trying to install package. \u2570\u2500> typed-ast note: This is an issue with the package mentioned above, not pip. hint: See above for output from the failure. at ~/.poetry/lib/poetry/utils/env.py:1195 in _run 1191\u2502 output = subprocess.check_output( 1192\u2502 cmd, stderr=subprocess.STDOUT, **kwargs 1193\u2502 ) 1194\u2502 except CalledProcessError as e: \u2192 1195\u2502 raise EnvCommandError(e, input=input_) 1196\u2502 1197\u2502 return decode(output) 1198\u2502 1199\u2502 def execute(self, bin, *args, **kwargs): This error is while installing Installing typed-ast (1.4.3) This package was a dependency of mypy (0.761). I changed the mypy version to 0.961 and it does not have this dependency.","title":"Solution"},{"location":"python_poetry_find_transitive_dependency/","text":"","title":"Python poetry find transitive dependency"},{"location":"python_poetry_install_pg_config_executable_not_found/","text":"Error pg_config executable not found while installing psycopg2 via poetry. Problem poetry install returned following error. Installing dependencies from lock file Package operations: 1 install, 0 updates, 0 removals \u2022 Installing psycopg2-binary (2.9.3): Failed EnvCommandError Command ['~/.../venv/bin/pip', 'install', '--no-deps', 'file://~/Library/Caches/pypoetry/artifacts/.../psycopg2-binary-2.9.3.tar.gz'] errored with the following return code 1, and output: Processing ~/Library/Caches/pypoetry/artifacts/.../psycopg2-binary-2.9.3.tar.gz Preparing metadata (setup.py): started Preparing metadata (setup.py): finished with status 'error' ERROR: Command errored out with exit status 1: command: ~/.../venv/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/47/.../T/pip-req-build-lvsj6n0r/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/47/.../T/pip-req-build-lvsj6n0r/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/47/.../T/pip-pip-egg-info-lgklgcy5 cwd: /private/var/folders/47/.../T/pip-req-build-lvsj6n0r/ Complete output (20 lines): running egg_info creating /private/var/folders/47/.../T/pip-pip-egg-info-lgklgcy5/psycopg2_binary.egg-info writing manifest file '/private/var/folders/47/.../T/pip-pip-egg-info-lgklgcy5/psycopg2_binary.egg-info/SOURCES.txt' Error: pg_config executable not found. pg_config is required to build psycopg2 from source. Please add the directory containing pg_config to the $PATH or specify the full executable path with the option: python setup.py build_ext --pg-config /path/to/pg_config build ... or with the pg_config option in 'setup.cfg'. If you prefer to avoid building psycopg2 from source, please install the PyPI 'psycopg2-binary' package instead. For further information please check the 'doc/src/install.rst' file (also at <https://www.psycopg.org/docs/install.html>). ---------------------------------------- WARNING: Discarding file://~/Library/Caches/pypoetry/artifacts/ba/42/10/.../psycopg2-binary-2.9.3.tar.gz. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output. ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output. WARNING: You are using pip version 21.3.1; however, version 22.1.2 is available. You should consider upgrading via the '~/.../venv/bin/python -m pip install --upgrade pip' command. at ~/.poetry/lib/poetry/utils/env.py:1195 in _run 1191\u2502 output = subprocess.check_output( 1192\u2502 cmd, stderr=subprocess.STDOUT, **kwargs 1193\u2502 ) 1194\u2502 except CalledProcessError as e: \u2192 1195\u2502 raise EnvCommandError(e, input=input_) 1196\u2502 1197\u2502 return decode(output) 1198\u2502 1199\u2502 def execute(self, bin, *args, **kwargs): Solution Check if pg_config is installed or not. which pg_config -> pg_config not found Ref: https://stackoverflow.com/a/24645416 brew install postgresql which pg_config -> /opt/homebrew/bin/pg_config poetry install -> success","title":"Python poetry install pg config executable not found"},{"location":"python_poetry_install_pg_config_executable_not_found/#problem","text":"poetry install returned following error. Installing dependencies from lock file Package operations: 1 install, 0 updates, 0 removals \u2022 Installing psycopg2-binary (2.9.3): Failed EnvCommandError Command ['~/.../venv/bin/pip', 'install', '--no-deps', 'file://~/Library/Caches/pypoetry/artifacts/.../psycopg2-binary-2.9.3.tar.gz'] errored with the following return code 1, and output: Processing ~/Library/Caches/pypoetry/artifacts/.../psycopg2-binary-2.9.3.tar.gz Preparing metadata (setup.py): started Preparing metadata (setup.py): finished with status 'error' ERROR: Command errored out with exit status 1: command: ~/.../venv/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/47/.../T/pip-req-build-lvsj6n0r/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/47/.../T/pip-req-build-lvsj6n0r/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/47/.../T/pip-pip-egg-info-lgklgcy5 cwd: /private/var/folders/47/.../T/pip-req-build-lvsj6n0r/ Complete output (20 lines): running egg_info creating /private/var/folders/47/.../T/pip-pip-egg-info-lgklgcy5/psycopg2_binary.egg-info writing manifest file '/private/var/folders/47/.../T/pip-pip-egg-info-lgklgcy5/psycopg2_binary.egg-info/SOURCES.txt' Error: pg_config executable not found. pg_config is required to build psycopg2 from source. Please add the directory containing pg_config to the $PATH or specify the full executable path with the option: python setup.py build_ext --pg-config /path/to/pg_config build ... or with the pg_config option in 'setup.cfg'. If you prefer to avoid building psycopg2 from source, please install the PyPI 'psycopg2-binary' package instead. For further information please check the 'doc/src/install.rst' file (also at <https://www.psycopg.org/docs/install.html>). ---------------------------------------- WARNING: Discarding file://~/Library/Caches/pypoetry/artifacts/ba/42/10/.../psycopg2-binary-2.9.3.tar.gz. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output. ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output. WARNING: You are using pip version 21.3.1; however, version 22.1.2 is available. You should consider upgrading via the '~/.../venv/bin/python -m pip install --upgrade pip' command. at ~/.poetry/lib/poetry/utils/env.py:1195 in _run 1191\u2502 output = subprocess.check_output( 1192\u2502 cmd, stderr=subprocess.STDOUT, **kwargs 1193\u2502 ) 1194\u2502 except CalledProcessError as e: \u2192 1195\u2502 raise EnvCommandError(e, input=input_) 1196\u2502 1197\u2502 return decode(output) 1198\u2502 1199\u2502 def execute(self, bin, *args, **kwargs):","title":"Problem"},{"location":"python_poetry_install_pg_config_executable_not_found/#solution","text":"Check if pg_config is installed or not. which pg_config -> pg_config not found Ref: https://stackoverflow.com/a/24645416 brew install postgresql which pg_config -> /opt/homebrew/bin/pg_config poetry install -> success","title":"Solution"},{"location":"python_poetry_pytest_required_field_lineno_missing_from_alias/","text":"Python Poetry Pytest TypeError: required field \"lineno\" missing from alias poetry run pytest returns Traceback (most recent call last): File \"~/.../venv/bin/pytest\", line 8, in <module> sys.exit(main()) File \"~/.../venv/lib/python3.10/site-packages/_pytest/config/__init__.py\", line 71, in main config = _prepareconfig(args, plugins) File \"~/.../venv/lib/python3.10/site-packages/_pytest/config/__init__.py\", line 215, in _prepareconfig return pluginmanager.hook.pytest_cmdline_parse( File \"~/.../venv/lib/python3.10/site-packages/pluggy/hooks.py\", line 286, in __call__ return self._hookexec(self, self.get_hookimpls(), kwargs) File \"~/.../venv/lib/python3.10/site-packages/pluggy/manager.py\", line 93, in _hookexec return self._inner_hookexec(hook, methods, kwargs) File \"~/.../venv/lib/python3.10/site-packages/pluggy/manager.py\", line 84, in <lambda> self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall( File \"~/.../venv/lib/python3.10/site-packages/pluggy/callers.py\", line 203, in _multicall gen.send(outcome) File \"~/.../venv/lib/python3.10/site-packages/_pytest/helpconfig.py\", line 89, in pytest_cmdline_parse config = outcome.get_result() File \"~/.../venv/lib/python3.10/site-packages/pluggy/callers.py\", line 80, in get_result raise ex[1].with_traceback(ex[2]) File \"~/.../venv/lib/python3.10/site-packages/pluggy/callers.py\", line 187, in _multicall res = hook_impl.function(*args) File \"~/.../venv/lib/python3.10/site-packages/_pytest/config/__init__.py\", line 733, in pytest_cmdline_parse self.parse(args) File \"~/.../venv/lib/python3.10/site-packages/_pytest/config/__init__.py\", line 940, in parse self._preparse(args, addopts=addopts) File \"~/.../venv/lib/python3.10/site-packages/_pytest/config/__init__.py\", line 887, in _preparse self.pluginmanager.load_setuptools_entrypoints(\"pytest11\") File \"~/.../venv/lib/python3.10/site-packages/pluggy/manager.py\", line 299, in load_setuptools_entrypoints plugin = ep.load() File \"~/.pyenv/versions/3.10.5/lib/python3.10/importlib/metadata/__init__.py\", line 171, in load module = import_module(match.group('module')) File \"~/.pyenv/versions/3.10.5/lib/python3.10/importlib/__init__.py\", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) File \"<frozen importlib._bootstrap>\", line 1050, in _gcd_import File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked File \"~/.../venv/lib/python3.10/site-packages/_pytest/assertion/rewrite.py\", line 133, in exec_module source_stat, co = _rewrite_test(fn, self.config) File \"~/.../venv/lib/python3.10/site-packages/_pytest/assertion/rewrite.py\", line 284, in _rewrite_test co = compile(tree, fn, \"exec\", dont_inherit=True) TypeError: required field \"lineno\" missing from alias pytest -V or pytest --version also reports the same error. This post claims it is fixed in pytest verion 6.2.5 set pytest = \"==7.1.2\" poetry update pytest --version -> pytest 7.1.2 run again poetry run pytest It worked.","title":"Python Poetry Pytest TypeError: required field \"lineno\" missing from alias"},{"location":"python_poetry_pytest_required_field_lineno_missing_from_alias/#python-poetry-pytest-typeerror-required-field-lineno-missing-from-alias","text":"poetry run pytest returns Traceback (most recent call last): File \"~/.../venv/bin/pytest\", line 8, in <module> sys.exit(main()) File \"~/.../venv/lib/python3.10/site-packages/_pytest/config/__init__.py\", line 71, in main config = _prepareconfig(args, plugins) File \"~/.../venv/lib/python3.10/site-packages/_pytest/config/__init__.py\", line 215, in _prepareconfig return pluginmanager.hook.pytest_cmdline_parse( File \"~/.../venv/lib/python3.10/site-packages/pluggy/hooks.py\", line 286, in __call__ return self._hookexec(self, self.get_hookimpls(), kwargs) File \"~/.../venv/lib/python3.10/site-packages/pluggy/manager.py\", line 93, in _hookexec return self._inner_hookexec(hook, methods, kwargs) File \"~/.../venv/lib/python3.10/site-packages/pluggy/manager.py\", line 84, in <lambda> self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall( File \"~/.../venv/lib/python3.10/site-packages/pluggy/callers.py\", line 203, in _multicall gen.send(outcome) File \"~/.../venv/lib/python3.10/site-packages/_pytest/helpconfig.py\", line 89, in pytest_cmdline_parse config = outcome.get_result() File \"~/.../venv/lib/python3.10/site-packages/pluggy/callers.py\", line 80, in get_result raise ex[1].with_traceback(ex[2]) File \"~/.../venv/lib/python3.10/site-packages/pluggy/callers.py\", line 187, in _multicall res = hook_impl.function(*args) File \"~/.../venv/lib/python3.10/site-packages/_pytest/config/__init__.py\", line 733, in pytest_cmdline_parse self.parse(args) File \"~/.../venv/lib/python3.10/site-packages/_pytest/config/__init__.py\", line 940, in parse self._preparse(args, addopts=addopts) File \"~/.../venv/lib/python3.10/site-packages/_pytest/config/__init__.py\", line 887, in _preparse self.pluginmanager.load_setuptools_entrypoints(\"pytest11\") File \"~/.../venv/lib/python3.10/site-packages/pluggy/manager.py\", line 299, in load_setuptools_entrypoints plugin = ep.load() File \"~/.pyenv/versions/3.10.5/lib/python3.10/importlib/metadata/__init__.py\", line 171, in load module = import_module(match.group('module')) File \"~/.pyenv/versions/3.10.5/lib/python3.10/importlib/__init__.py\", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) File \"<frozen importlib._bootstrap>\", line 1050, in _gcd_import File \"<frozen importlib._bootstrap>\", line 1027, in _find_and_load File \"<frozen importlib._bootstrap>\", line 1006, in _find_and_load_unlocked File \"<frozen importlib._bootstrap>\", line 688, in _load_unlocked File \"~/.../venv/lib/python3.10/site-packages/_pytest/assertion/rewrite.py\", line 133, in exec_module source_stat, co = _rewrite_test(fn, self.config) File \"~/.../venv/lib/python3.10/site-packages/_pytest/assertion/rewrite.py\", line 284, in _rewrite_test co = compile(tree, fn, \"exec\", dont_inherit=True) TypeError: required field \"lineno\" missing from alias pytest -V or pytest --version also reports the same error. This post claims it is fixed in pytest verion 6.2.5 set pytest = \"==7.1.2\" poetry update pytest --version -> pytest 7.1.2 run again poetry run pytest It worked.","title":"Python Poetry Pytest TypeError: required field \"lineno\" missing from alias"},{"location":"python_poetry_run_isort_no_such_file_or_directory/","text":"Python - Poetry - isort - No such file or directory ~/.local/bin/isort Problem: No such file or directory ~/.local/bin/isort poetry run isort returns FileNotFoundError [Errno 2] No such file or directory: b'/Users/anil/.local/bin/isort' at ~/.pyenv/versions/3.10.5/lib/python3.10/os.py:607 in _execvpe 603\u2502 path_list = map(fsencode, path_list) 604\u2502 for dir in path_list: 605\u2502 fullname = path.join(dir, file) 606\u2502 try: \u2192 607\u2502 exec_func(fullname, *argrest) 608\u2502 except (FileNotFoundError, NotADirectoryError) as e: 609\u2502 last_exc = e 610\u2502 except OSError as e: 611\u2502 last_exc = e Solution Check if all the dependencies are installed properly. poetry install returns Installing dependencies from lock file Package operations: 323 installs, 1 update, 0 removals \u2022 Installing numpy (1.21.1): ... ---------------------------------------- ERROR: Failed building wheel for numpy Failed to build numpy ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects WARNING: You are using pip version 21.3.1; however, version 22.1.2 is available. You should consider upgrading via the '/Users/anil/.../venv/bin/python -m pip install --upgrade pip' command. at ~/.poetry/lib/poetry/utils/env.py:1195 in _run 1191\u2502 output = subprocess.check_output( 1192\u2502 cmd, stderr=subprocess.STDOUT, **kwargs 1193\u2502 ) 1194\u2502 except CalledProcessError as e: \u2192 1195\u2502 raise EnvCommandError(e, input=input_) 1196\u2502 1197\u2502 return decode(output) 1198\u2502 1199\u2502 def execute(self, bin, *args, **kwargs): try to install directly via pip pip install numpy and then try again poetry install returns Installing dependencies from lock file No dependencies to install or update Done","title":"Python - Poetry - isort - No such file or directory ~/.local/bin/isort"},{"location":"python_poetry_run_isort_no_such_file_or_directory/#python-poetry-isort-no-such-file-or-directory-localbinisort","text":"","title":"Python - Poetry - isort - No such file or directory ~/.local/bin/isort"},{"location":"python_poetry_run_isort_no_such_file_or_directory/#problem-no-such-file-or-directory-localbinisort","text":"poetry run isort returns FileNotFoundError [Errno 2] No such file or directory: b'/Users/anil/.local/bin/isort' at ~/.pyenv/versions/3.10.5/lib/python3.10/os.py:607 in _execvpe 603\u2502 path_list = map(fsencode, path_list) 604\u2502 for dir in path_list: 605\u2502 fullname = path.join(dir, file) 606\u2502 try: \u2192 607\u2502 exec_func(fullname, *argrest) 608\u2502 except (FileNotFoundError, NotADirectoryError) as e: 609\u2502 last_exc = e 610\u2502 except OSError as e: 611\u2502 last_exc = e","title":"Problem: No such file or directory ~/.local/bin/isort"},{"location":"python_poetry_run_isort_no_such_file_or_directory/#solution","text":"Check if all the dependencies are installed properly. poetry install returns Installing dependencies from lock file Package operations: 323 installs, 1 update, 0 removals \u2022 Installing numpy (1.21.1): ... ---------------------------------------- ERROR: Failed building wheel for numpy Failed to build numpy ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects WARNING: You are using pip version 21.3.1; however, version 22.1.2 is available. You should consider upgrading via the '/Users/anil/.../venv/bin/python -m pip install --upgrade pip' command. at ~/.poetry/lib/poetry/utils/env.py:1195 in _run 1191\u2502 output = subprocess.check_output( 1192\u2502 cmd, stderr=subprocess.STDOUT, **kwargs 1193\u2502 ) 1194\u2502 except CalledProcessError as e: \u2192 1195\u2502 raise EnvCommandError(e, input=input_) 1196\u2502 1197\u2502 return decode(output) 1198\u2502 1199\u2502 def execute(self, bin, *args, **kwargs): try to install directly via pip pip install numpy and then try again poetry install returns Installing dependencies from lock file No dependencies to install or update Done","title":"Solution"},{"location":"spring_boot_set_log_level_of_package/","text":"Spring boot set the log level for a package In the application.yaml file ... logging: level: org: zalando: fahrschein: trace ...","title":"Spring boot set the log level for a package"},{"location":"spring_boot_set_log_level_of_package/#spring-boot-set-the-log-level-for-a-package","text":"In the application.yaml file ... logging: level: org: zalando: fahrschein: trace ...","title":"Spring boot set the log level for a package"},{"location":"ubuntu_append_text_at_the_end_of_file/","text":"echo \"alias myapp-status='systemctl status my-app.service'\" >> ~/.bashrc","title":"Ubuntu append text at the end of file"},{"location":"ubuntu_create_service/","text":"Ubuntu - Create a new systemd service How to create a new systemd service on ubuntu create a file /etc/systemd/system/my-app.service with the following content [Unit] Description=My Service After=network.target [Service] Environment=\"HOME=/root\" EnvironmentFile=/home/anil/prod.env ExecStart=/home/anil/jdk-15.0.1/bin/java -jar /home/anil/my-app.jar Type=simple Restart=always [Install] WantedBy=default.target Check if the service is created: $ systemctl status my-app.service \u25cf my-app.service - My Service Loaded: loaded (/etc/systemd/system/my-app.service; disabled; vendor preset: enabled) Active: inactive (dead) Create aliases to manage service echo \"alias myapp-status='systemctl status my-app.service'\" >> ~/.bashrc echo \"alias myapp-start='systemctl start my-app.service'\" >> ~/.bashrc echo \"alias myapp-restart='systemctl restart my-app.service'\" >> ~/.bashrc echo \"alias myapp-stop='systemctl stop my-app.service'\" >> ~/.bashrc echo \"alias myapp-logs='journalctl -u my-app.service -e -f'\" >> ~/.bashrc ref: manpage","title":"Ubuntu - Create a new systemd service"},{"location":"ubuntu_create_service/#ubuntu-create-a-new-systemd-service","text":"","title":"Ubuntu - Create a new systemd service"},{"location":"ubuntu_create_service/#how-to-create-a-new-systemd-service-on-ubuntu","text":"create a file /etc/systemd/system/my-app.service with the following content [Unit] Description=My Service After=network.target [Service] Environment=\"HOME=/root\" EnvironmentFile=/home/anil/prod.env ExecStart=/home/anil/jdk-15.0.1/bin/java -jar /home/anil/my-app.jar Type=simple Restart=always [Install] WantedBy=default.target Check if the service is created: $ systemctl status my-app.service \u25cf my-app.service - My Service Loaded: loaded (/etc/systemd/system/my-app.service; disabled; vendor preset: enabled) Active: inactive (dead) Create aliases to manage service echo \"alias myapp-status='systemctl status my-app.service'\" >> ~/.bashrc echo \"alias myapp-start='systemctl start my-app.service'\" >> ~/.bashrc echo \"alias myapp-restart='systemctl restart my-app.service'\" >> ~/.bashrc echo \"alias myapp-stop='systemctl stop my-app.service'\" >> ~/.bashrc echo \"alias myapp-logs='journalctl -u my-app.service -e -f'\" >> ~/.bashrc ref: manpage","title":"How to create a new systemd service on ubuntu"},{"location":"ubuntu_enable_ssh_from_network/","text":"Ubuntu - Enable ssh from local network How can I ssh into a ubuntu machine which is connected to the same wifi? try $ ssh anil@192.168.0.20 ssh: connect to host 192.168.0.20 port 22: Connection refused Install openssh server on ubuntu. sudo apt-get install openssh-server try again: $ ssh anil@192.168.0.20 anil@anil-notebook:~$ It worked!","title":"Ubuntu - Enable ssh from local network"},{"location":"ubuntu_enable_ssh_from_network/#ubuntu-enable-ssh-from-local-network","text":"How can I ssh into a ubuntu machine which is connected to the same wifi? try $ ssh anil@192.168.0.20 ssh: connect to host 192.168.0.20 port 22: Connection refused Install openssh server on ubuntu. sudo apt-get install openssh-server try again: $ ssh anil@192.168.0.20 anil@anil-notebook:~$ It worked!","title":"Ubuntu - Enable ssh from local network"},{"location":"vscode_shortcuts/","text":"VS Code shortcuts Open cpmmand palette \u2318 \u21e7 P View markdown preview \u2318 \u21e7 V copy line \u2325 \u21e7 \u2193 OR \u2325 \u21e7 \u2191 Move line \u2325 \u2193 OR \u2325 \u2191 Reveal file in explorer \u2318 \u21e7 P -> type reveal -> choose reveal active file in explorer view Delete file \u2318 \u232b vscode change / switch editor tab or files \u2318 \u2325 \u2190 or \u2318 \u2325 \u2192","title":"VS Code shortcuts"},{"location":"vscode_shortcuts/#vs-code-shortcuts","text":"","title":"VS Code shortcuts"},{"location":"vscode_shortcuts/#open-cpmmand-palette","text":"\u2318 \u21e7 P","title":"Open cpmmand palette"},{"location":"vscode_shortcuts/#view-markdown-preview","text":"\u2318 \u21e7 V","title":"View markdown preview"},{"location":"vscode_shortcuts/#copy-line","text":"\u2325 \u21e7 \u2193 OR \u2325 \u21e7 \u2191","title":"copy line"},{"location":"vscode_shortcuts/#move-line","text":"\u2325 \u2193 OR \u2325 \u2191","title":"Move line"},{"location":"vscode_shortcuts/#reveal-file-in-explorer","text":"\u2318 \u21e7 P -> type reveal -> choose reveal active file in explorer view","title":"Reveal file in explorer"},{"location":"vscode_shortcuts/#delete-file","text":"\u2318 \u232b","title":"Delete file"},{"location":"vscode_shortcuts/#vscode-change-switch-editor-tab-or-files","text":"\u2318 \u2325 \u2190 or \u2318 \u2325 \u2192","title":"vscode change / switch editor tab or files"},{"location":"what_is_LSP/","text":"What is LSP (Liskov substitution principle) TODO","title":"What is LSP (Liskov substitution principle)"},{"location":"what_is_LSP/#what-is-lsp-liskov-substitution-principle","text":"","title":"What is LSP (Liskov substitution principle)"},{"location":"what_is_LSP/#todo","text":"","title":"TODO"}]}